#!/bin/bash
find . "-name \*.gif -type f -printf "%f\n" | LC_COLLATE=C sort --ignore-case | rev | cut -c 5- | rev"find . -name *.gif -type f | rev | cut -d . --complement  -f 1 | cut -d / -f 1 | rev | LC_ALL=C  sort -f
